import{a as v,S as w,i}from"./assets/vendor-BkC4bTqC.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const E="55187145-d3b914f8bfc13386f944f455c",P="https://pixabay.com/api/";async function f(t,r=1){return(await v.get(P,{params:{key:E,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:15}})).data}let u;function y(t){const r=document.querySelector(".gallery"),s=t.map(({webformatURL:n,largeImageURL:e,tags:o,likes:a,views:b,comments:S,downloads:q})=>`
      <li class="gallery-item">
        <a href="${e}">
          <img src="${n}" alt="${o}" />
        </a>
        <div class="info">
          <p>Likes: ${a}</p>
          <p>Views: ${b}</p>
          <p>Comments: ${S}</p>
          <p>Downloads: ${q}</p>
        </div>
      </li>
    `).join("");r.insertAdjacentHTML("beforeend",s),u?u.refresh():u=new w(".gallery a")}function $(){document.querySelector(".gallery").innerHTML=""}function m(){document.querySelector(".loader").style.display="block"}function p(){document.querySelector(".loader").style.display="none"}function h(){const t=document.querySelector(".load-more");t&&(t.style.display="block")}function g(){const t=document.querySelector(".load-more");t&&(t.style.display="none")}const B=document.querySelector(".form");let l="",c=1,d=0;const L=15;B.addEventListener("submit",async t=>{if(t.preventDefault(),l=t.target.elements["search-text"].value.trim(),!!l){c=1,$(),g(),m();try{const r=await f(l,c);if(d=r.totalHits,!r.hits.length){i.info({message:"Sorry, there are no images matching your search query."});return}if(y(r.hits),d<=L){i.info({message:"We're sorry, but you've reached the end of search results."});return}h()}catch{i.error({message:"Error fetching images"})}finally{p()}}});document.querySelector(".load-more").addEventListener("click",async()=>{c+=1,g(),m();try{const t=await f(l,c);if(y(t.hits),c*L>=d){i.info({message:"We're sorry, but you've reached the end of search results."});return}h();const n=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:n*2,behavior:"smooth"})}catch{i.error({message:"Error loading more images"})}finally{p()}});
//# sourceMappingURL=index.js.map
